services:

  front_end_db:
    image: postgres:latest
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

  browse_problems_db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

  buy_credits_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

  problem_stats_db:
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

  manage_problem_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

  front_end_service:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4007:4007"
    depends_on:
      - front_end_db
    environment:
      - DB_HOST=front_end_db
      - DB_PORT=5432
      - DB=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_TIMEZONE=UTC
      - DB_SCHEMA=myschema
      - BASE_URL= http://localhost:4007
      - SECRET_SESSION_STRING=9a845c30be6838b5ea4db5343a71a234
      - SECRET_ENCRYPT=9a845c30be6838b5ea4db5343a71a234
      - SECRET_STRING_SERVICES=9a845c30be6838b5ea4db5343a71a234

  browse_problems_service:
    build:
      context: ./browse-problems-service
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    depends_on:
      - browse_problems_db
    environment:
      - DB_HOST=browse_problems_db
      - DB_PORT=5435
      - DB=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_TIMEZONE=UTC
      - DB_SCHEMA=myschema
      - BASE_URL=- BASE_URL= http://localhost:4003
      - SECRET_STRING_SERVICES=9a845c30be6838b5ea4db5343a71a234
      - SECRET_ENCRYPT=9a845c30be6838b5ea4db5343a71a234

  submit_problem_service:
    build:
      context: ./submit-problem-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - BASE_URL= http://localhost:4001
      - SECRET_ENCRYPT=9a845c30be6838b5ea4db5343a71a234
      - SECRET_STRING_SERVICES=9a845c30be6838b5ea4db5343a71a234
