services:

  # Front-end Database
  front_end_db:
    image: postgres:latest
    ports:
      - "5438:5432"                   # Maps host port 5438 to container port 5432
    environment:
      - POSTGRES_USER=myuser          # Username for the PostgreSQL database
      - POSTGRES_PASSWORD=mypassword  # Password for the PostgreSQL database
      - POSTGRES_DB=mydatabase        # Name of the PostgreSQL database

  front_end_service:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4007:4007"
    depends_on:
      - front_end_db                        # Specify that this service depends on the availability of the front_end_db service
    environment:
      - DB_HOST=front_end_db         # Hostname or IP address of the front-end database server
      - DB_PORT=5432                        # Port number on which the front-end database server is listening
      - DB=mydatabase                       # Name of the front-end database
      - DB_USER=myuser                      # Username for the front-end database
      - DB_PASS=mypassword                  # Password for the front-end database
      - DB_TIMEZONE=UTC                     # Timezone for the front-end database
      - DB_SCHEMA=myschema                  # Schema name for the front-end database
      - BASE_URL= http://localhost:4007              # Base URL for the front-end service
      - SECRET_SESSION_STRING=9a845c30be6838b5ea4db5343a71a234    # Secret ingredient for The Powerpuff Girls

